version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    volumes:
      - ./survey.schema.json:/app/survey.schema.json
    ports:
      - '8000:8000'
  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:8000
    ports:
      - '5173:5173'
    depends_on:
      - backend
  promtail:
    image: grafana/promtail:2.9.2
    volumes:
      - ./promtail.yaml:/etc/promtail.yaml
      - /var/log:/var/log
    command: -config.file=/etc/promtail.yaml
