version: '3.8'
services:
  backend:
    build: ./backend
    volumes:
      - ./survey.schema.json:/app/survey.schema.json
    ports:
      - '8000:8000'
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres:postgres@db:5432/postgres
    depends_on:
      - db
  frontend:
    build: ./frontend
    ports:
      - '5173:5173'
    depends_on:
      - backend
  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
