name: CI/CD
on:
  push:
    branches: [main]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: '3.11'
      - name: Install backend deps
        run: |
          python -m pip install -r backend/requirements.txt bandit
      - name: Backend tests
        run: pytest backend/app/tests
      - name: Security scan
        run: bandit -r backend/app
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: Install frontend deps
        run: npm install --prefix frontend
      - name: Frontend tests
        run: npm test --prefix frontend
      - name: NPM audit
        run: npm audit --prefix frontend --audit-level=high

  deploy:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: railwayapp/railway-cli-action@v1
        with:
          railwayToken: ${{ secrets.RAILWAY_TOKEN }}
      - name: Deploy
        run: railway up --service backend
